import Head from 'next/head'
import Weather from '../components/Weather'
import Spinner from '../components/Spinner'
import Search from '../components/Search'
import Overlay from '../components/Overlay'
import { useWeather } from '../hooks/weather_api'

export default function Home() {
  const {loading, fetchWeather, setCity, weather} = useWeather()

	if (loading) {
		return <Spinner />
	} else {
		return (
			<div>
				<Head>
					<title>Weather App</title>
					<meta name='description' content='Generated by create next app' />
					<link rel='icon' href='/favicon.ico' />
				</Head>
				<Overlay />
				<Search fetchWeather={fetchWeather} setCity={setCity} />
				{weather.main && <Weather data={weather} />}
			</div>
		)
	}
}
